name: deploy_to_gh_pages
on:
  push:
    branches: [ master ]

jobs:

  build_dist:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: |
          npm i
          npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: dist_artifact
          path: dist/**/*
  
  deploy_dist:
    runs-on: ubuntu-18.04
    needs: build_dist
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages

      - run: rm -R ./*

      - uses: actions/download-artifact@v2
        with:
          name: dist_artifact
          path: ./

      - run: |
          git config --local user.email "posts_hook@github.com"
          git config --local user.name "Posts Hook"
          git add .
          git commit -m "[CI:deploy] deploy_dist job"

      - uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}